config/routes.rb
Rails.application.routes.draw do

  resources :delivery_infos
  resources :orders
  resources :ingredients
  resources :recipes
  resources :crusts
  resources :pizzas
  get 'home/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"
end

app/models/delivery_info.rb
class DeliveryInfo < ApplicationRecord
  belongs_to :user
  validates :phone_number,  presence: true, numericality: { only_integer: true }
  validates :user_id, uniqueness: true
end

app/controllers/delivery_infos_controller.rb
class DeliveryInfosController < ApplicationController
  before_action :set_delivery_info, only: [:show, :edit, :update, :destroy]

  # GET /delivery_infos
  # GET /delivery_infos.json
  def index
    @delivery_infos = DeliveryInfo.where(user_id: current_user.id)
  end

  # GET /delivery_infos/1
  # GET /delivery_infos/1.json
  def show
  end

  # GET /delivery_infos/new
  def new
    @delivery_info = DeliveryInfo.new
    @delivery_info.user_id = current_user.id
  end

  # GET /delivery_infos/1/edit
  def edit
  end

  # POST /delivery_infos
  # POST /delivery_infos.json
  def create
    @delivery_info = DeliveryInfo.new(delivery_info_params)

    respond_to do |format|
      if @delivery_info.save
        format.html { redirect_to @delivery_info, notice: 'Delivery info was successfully created.' }
        format.json { render :show, status: :created, location: @delivery_info }
      else
        format.html { render :new }
        format.json { render json: @delivery_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /delivery_infos/1
  # PATCH/PUT /delivery_infos/1.json
  def update
    respond_to do |format|
      if @delivery_info.update(delivery_info_params)
        format.html { redirect_to @delivery_info, notice: 'Delivery info was successfully updated.' }
        format.json { render :show, status: :ok, location: @delivery_info }
      else
        format.html { render :edit }
        format.json { render json: @delivery_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /delivery_infos/1
  # DELETE /delivery_infos/1.json
  def destroy
    @delivery_info.destroy
    respond_to do |format|
      format.html { redirect_to delivery_infos_url, notice: 'Delivery info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delivery_info
      @delivery_info = DeliveryInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def delivery_info_params
      params.fetch(:delivery_info, {})
    end
end

app/helpers/delivery_infos_helper.rb
module DeliveryInfosHelper
end

app/views/delivery_infos/_form.html.erb
<%= form_with(model: delivery_info, local: true) do |form| %>
  <% if delivery_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(delivery_info.errors.count, "error") %> prohibited this delivery_info from being saved:</h2>

      <ul>
      <% delivery_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/delivery_infos/edit.html.erb
<h1>Editing Delivery Info</h1>

<%= render 'form', delivery_info: @delivery_info %>

<%= link_to 'Show', @delivery_info %> |
<%= link_to 'Back', delivery_infos_path %>

app/views/delivery_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Delivery Infos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @delivery_infos.each do |delivery_info| %>
      <tr>
        <td><%= link_to 'Show', delivery_info %></td>
        <td><%= link_to 'Edit', edit_delivery_info_path(delivery_info) %></td>
        <td><%= link_to 'Destroy', delivery_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Delivery Info', new_delivery_info_path %>

app/views/delivery_infos/new.html.erb
<h1>New Delivery Info</h1>

<%= render 'form', delivery_info: @delivery_info %>

<%= link_to 'Back', delivery_infos_path %>

app/views/delivery_infos/show.html.erb
<p id="notice"><%= notice %></p>

<div class = "row">

  <div class=" col-5">

    <div class=" row">
      <h2>PHONE NUMBER:</h2>
      <h2><%= @delivery_info.phone_number %></h2>
    </div>

    <div class=" row">
      <h2>address_line_1:</h2>
      <h2> <%= @delivery_info.address_line_1 %></h2>
    </div>

    <div class=" row">
      <h2>address_line_2:</h2>
      <h2> <%= @delivery_info.address_line_2 %></h2>
    </div>

  </div>

<%= link_to 'Edit', edit_delivery_info_path(@delivery_info) %> |
<%= link_to 'Back', delivery_infos_path %>







<